Update cf-tunnel-client.yml

diff --git a/.github/workflows/cf-tunnel-client.yml b/.github/workflows/cf-tunnel-client.yml
--- a/.github/workflows/cf-tunnel-client.yml
+++ b/.github/workflows/cf-tunnel-client.yml
@@ -36,52 +36,52 @@ jobs:
         if: always()
         uses: AnimMouse/cfworkerdemo/shutdown@main
         
-  test-macos:
-    runs-on: macos-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        version: [latest, 2023.8.1]
+  # test-macos:
+  #   runs-on: macos-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       version: [latest, 2023.8.1]
         
-    steps:
-      - name: Setup cloudflared using setup-cloudflared
-        uses: AnimMouse/cfworkerdemo@main
-        with:
-          cloudflare_tunnel_credential: ${{ secrets.CLOUDFLARE_TUNNEL_CREDENTIAL }}
-          cloudflare_tunnel_configuration: ${{ secrets.CLOUDFLARE_TUNNEL_CONFIGURATION_MACOS }}
-          cloudflare_tunnel_id: ${{ secrets.CLOUDFLARE_TUNNEL_ID }}
+  #   steps:
+  #     - name: Setup cloudflared using setup-cloudflared
+  #       uses: AnimMouse/cfworkerdemo@main
+  #       with:
+  #         cloudflare_tunnel_credential: ${{ secrets.CLOUDFLARE_TUNNEL_CREDENTIAL }}
+  #         cloudflare_tunnel_configuration: ${{ secrets.CLOUDFLARE_TUNNEL_CONFIGURATION_MACOS }}
+  #         cloudflare_tunnel_id: ${{ secrets.CLOUDFLARE_TUNNEL_ID }}
           
-      - name: Test cloudflared installed by setup-cloudflared using Python HTTP server for 1 minute
-        run: |
-          function timeout(){ perl -e 'alarm shift; exec @ARGV' "$@"; }
-          timeout 60 python3 -m http.server 8080 || true
+  #     - name: Test cloudflared installed by setup-cloudflared using Python HTTP server for 1 minute
+  #       run: |
+  #         function timeout(){ perl -e 'alarm shift; exec @ARGV' "$@"; }
+  #         timeout 60 python3 -m http.server 8080 || true
           
-      - name: Shutdown cloudflared using setup-cloudflared/shutdown
-        if: always()
-        uses: AnimMouse/cfworkerdemo/shutdown@main
+  #     - name: Shutdown cloudflared using setup-cloudflared/shutdown
+  #       if: always()
+  #       uses: AnimMouse/cfworkerdemo/shutdown@main
         
-  test-windows:
-    runs-on: windows-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        version: [latest, 2023.8.1]
+  # test-windows:
+  #   runs-on: windows-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       version: [latest, 2023.8.1]
         
-    steps:
-      - name: Setup cloudflared using setup-cloudflared
-        uses: AnimMouse/cfworkerdemo@main
-        with:
-          cloudflare_tunnel_credential: ${{ secrets.CLOUDFLARE_TUNNEL_CREDENTIAL }}
-          cloudflare_tunnel_configuration: ${{ secrets.CLOUDFLARE_TUNNEL_CONFIGURATION_WINDOWS }}
-          cloudflare_tunnel_id: ${{ secrets.CLOUDFLARE_TUNNEL_ID }}
+  #   steps:
+  #     - name: Setup cloudflared using setup-cloudflared
+  #       uses: AnimMouse/cfworkerdemo@main
+  #       with:
+  #         cloudflare_tunnel_credential: ${{ secrets.CLOUDFLARE_TUNNEL_CREDENTIAL }}
+  #         cloudflare_tunnel_configuration: ${{ secrets.CLOUDFLARE_TUNNEL_CONFIGURATION_WINDOWS }}
+  #         cloudflare_tunnel_id: ${{ secrets.CLOUDFLARE_TUNNEL_ID }}
           
-      - name: Test cloudflared installed by setup-cloudflared using Python HTTP server for 1 minute
-        run: |
-          $http_server = Start-Process "python" "-m http.server 8080" -PassThru
-          Wait-Process $http_server.Id -Timeout 60 -ErrorAction Ignore
-          $http_server.CloseMainWindow()
-          Wait-Process $http_server.Id
+  #     - name: Test cloudflared installed by setup-cloudflared using Python HTTP server for 1 minute
+  #       run: |
+  #         $http_server = Start-Process "python" "-m http.server 8080" -PassThru
+  #         Wait-Process $http_server.Id -Timeout 60 -ErrorAction Ignore
+  #         $http_server.CloseMainWindow()
+  #         Wait-Process $http_server.Id
           
-      - name: Shutdown cloudflared using cfworkerdemo/shutdown
-        if: always()
-        uses: AnimMouse/cfworkerdemo/shutdown@main
+  #     - name: Shutdown cloudflared using cfworkerdemo/shutdown
+  #       if: always()
+  #       uses: AnimMouse/cfworkerdemo/shutdown@main
